baseURL = "https://vigilant-franklin-221734.netlify.com/"
languageCode = "en-gb"
title = "Voter Tools"
theme = "mediumish-gohugo-theme"
copyright = "2019 Tech For UK. All rights reserved."

[permalinks]
  tactical = "/:section/:filename/"
  tools = "/:filename/"

[taxonomies]
  tacticalgoal = "tacticalgoals"
  tacticalmethod = "tacticalmethods"

[params]
  logo = "/images/logo.png"
  description = ""

[params.author]
  name = "Tech For UK"
  thumbnail = "/images/tech-for-uk.png"
  description = "Designed and built by members of the Tech For UK community."

[params.index]
#  picture = "/images/tbc.jpg"
  title = "Voter Tools"
  subtitle = ""
  alertbar = true

[params.social]
  github = "TechForUK"
  twitter = "TechForUK"

## Main Menu
[[menu.main]]
  name = "Tactical Voting Tools"
  weight = 100
  identifier = "tactical"
  url = "/tactical"
