baseURL = "https://unruffled-jang-9455e2.netlify.com/"
languageCode = "en-gb"
title = "Tactical Voting Tools"
theme = "mediumish-gohugo-theme"

[taxonomies]
  goals = "goals"
  methods = "methods"

[params]
  description ="All about voting tactically"

[params.author]
  name = "TBC"
#  thumbnail = "/images/tbc.jpg"
  description = "Who did this?"

[params.index]
#  picture = "/images/tbc.jpg"
  title = "Tactical Voting Tools"
  subtitle = "So many tactical voting sites, so little time!"
  mdtext = '''Work in progress!\
Comparison of [tactical voting sites](/reviews) coming soon'''
  alertbar = true

[params.social]
  github = "TechForUK"
  twitter = "TechForUK"

## Main Menu
[[menu.main]]
    name = "Register to vote"
    weight = 100
    identifier = "register"
    url = "https://www.gov.uk/register-to-vote"

#[[menu.main]]
#    name = "Reviews"
#    weight = 200
#    identifier = "reviews"
#    url = "/reviews"
